domainName: your-project-api-dev.example.com
corsAcceptOrigins: ""
notificationEmail: admin-dev@example.com

logLevel: INFO

#vpc:
#  securityGroupIds: your-security-group-id
#  subnetIds: your-subnet-id

logRetentionInDays: 5

logsRestApi:
  accessLogging: true # Optional configuration which enables or disables access logging. Defaults to true.
  executionLogging: true # Optional configuration which enables or disables execution logging. Defaults to true.
  level: INFO # Optional configuration which specifies the log level to use for execution logging. May be set to either INFO or ERROR.
  fullExecutionData: true # Optional configuration which specifies whether or not to log full requests/responses for execution logging. Defaults to true.

associateWafName: your-waf-name # If need to use WAF, set existing name of WebACL. If set not existing name, ignore this.

appConf:
  memorySize: 128 # MB
  timeout: 30 # s
  provisionedConcurrency: 2

media:
  s3BucketName: "your-project-media-dev.example.com"

## For Admin Console
#cognito:
#  region: "ap-northeast-1"
#  userpoolId: "ap-northeast-1_*********"
#  appClientId: "**************************"
#  checkTokenExpiration: True # If set Falsae, disable token expiration checking for testing purposes

dynamoDbBackupTargetTagValue: "none" # 'aws-backup':backup target / other value: not target

dynamodbConfig:
  sampleTable:
    billingMode: "PAY_PER_REQUEST" # Select 'PAY_PER_REQUEST' or 'PROVISIONED'
    provisionedThroughput:
      readCapacityUnits: 0
      writeCapacityUnits: 0
